version: '3.8'

services:
  # PostgreSQL база данных
  db:
    image: postgres:15-alpine
    container_name: home_db_dev
    environment:
      POSTGRES_DB: home_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - home_network_dev

  # Backend приложение (только для разработки)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: home_backend_dev
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/home_db
      - SECRET_KEY=dev-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=["http://localhost:3000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - home_network_dev
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data_dev:

networks:
  home_network_dev:
    driver: bridge
